import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {splitCents,compute,parsePaste,defaultSettings} from '../lib/model.ts';
const base=process.env.CALCUTTA_TEST_URL||'http://localhost:5173';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw Error('Acceptance writes are restricted to a local test server.');
let checks=0;function check(condition,label){assert.ok(condition,label);checks++;console.log('PASS '+label);}
const login=await fetch(base+'/signin-with-chatgpt?return_to=%2Fadmin',{redirect:'manual'}),cookie=login.headers.get('set-cookie')?.split(';')[0];
check(!!cookie,'Local simulated sign-in provides a session');
let eventId,d;
async function read(){const r=await fetch(base+'/api/admin'+(eventId?'?event='+eventId:''),{headers:{cookie}});assert.equal(r.status,200);const b=await r.json();d=b.data;return b;}
async function pub(extra=''){const r=await fetch(base+'/api/public?event='+eventId+extra);return {r,b:r.status===204?null:await r.json()};}
async function send(action,payload={},opts={}){const body={action,payload,eventId,revision:d?.event.revision,requestId:crypto.randomUUID(),...opts};const r=await fetch(base+'/api/admin',{method:'POST',headers:{cookie,origin:base,'content-type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(opts.expected){assert.equal(r.status,opts.expected,JSON.stringify(b));return {r,b,body};}assert.equal(r.status,200,action+': '+JSON.stringify(b));if(b.eventId)eventId=b.eventId;await read();return {r,b,body};}
await read();
check((await fetch(base+'/api/admin')).status===403,'Anonymous admin API denied');
check((await fetch(base+'/admin',{redirect:'manual'})).status===307,'Anonymous admin page redirects to sign-in');
check((await fetch(base+'/api/admin',{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify({action:'load_demo',requestId:crypto.randomUUID()})})).status===403,'Anonymous writes denied');
check((await fetch(base+'/api/admin',{headers:{'oai-authenticated-user-id':'forged','oai-authenticated-user-email':'seedy@sites.test'}})).status===403,'Forged identity headers stripped by local dispatcher');
check((await fetch(base+'/api/admin',{method:'POST',headers:{cookie,origin:'https://attacker.example','content-type':'application/json'},body:'{}'})).status===403,'Cross-origin mutations denied');
await send('create_event',{name:'Acceptance rehearsal '+new Date().toISOString(),course:'Fictional test course'});
writeFileSync('.sites-runtime/acceptance-event.json',JSON.stringify({eventId}));check(d.event.status==='SETUP','Create persistent tournament');
await send('flight_save',{name:'Championship Flight',color:'#b79a59',ownPool:true});
await send('flight_save',{name:'First Flight',color:'#879771',ownPool:true});const f1=d.flights[0].id,f2=d.flights[1].id;
check(d.flights.length===2,'Create both flights');
await send('team_save',{name:'Team A',players:['Avery North','Jordan West'],flightId:f1,privateNotes:'SECRET_TEAM_NOTES'});const tA=d.teams[0].id;
const parsed=parsePaste('Team B | Blake South | Casey East | Championship Flight | 8.4\nTeam C | Devon Fields | Emery Lake | First Flight | 14.7');
await send('team_import',{teams:parsed.map(row=>({name:row[0],players:[row[1],row[2]],flightId:row[3]==='Championship Flight'?f1:f2,handicap:Number(row[4])}))});
check(d.teams.length===3,'Bulk paste adds editable relational teams');const tB=d.teams[1].id,tC=d.teams[2].id;
await send('team_save',{name:'Four person team',players:['One','Two','Three','Four'],flightId:f2});check(d.teams.at(-1).players.length===4,'Teams support four players');const t4=d.teams.at(-1).id;
await send('team_save',{name:'Invalid team',players:['1','2','3','4','5'],flightId:f2},{expected:400});check(d.teams.length===4,'Five players rejected');
await send('buyer_save',{name:'Buyer A',contact:'PRIVATE_CONTACT_A',privateNotes:'SECRET_BUYER_NOTES'});const bA=d.buyers.find(b=>b.name==='Buyer A').id;
await send('buyer_save',{name:'Buyer B',group:'Table 6',contact:'PRIVATE_CONTACT_B'});const bB=d.buyers.find(b=>b.name==='Buyer B').id;
await send('buyer_save',{name:'buyer a'},{expected:400});check(d.buyers.length===2,'Case-insensitive duplicate buyer rejected');
await send('team_reorder',{ids:[tA,tB,t4,tC]});check(d.teams[2].id===t4,'Reorder saved');
await send('status',{status:'LIVE'});check(d.state.teamId===tA,'Start places Team A on block');
await send('bid',{teamId:tA,buyerId:bA,amount:50000});let publicData=(await pub()).b;check(publicData.state.bid===50000&&publicData.state.buyer==='Buyer A','Public viewer reads $500 / Buyer A');
const boardRev=d.event.boardRevision,revision=d.event.revision;
await send('bid',{teamId:tA,buyerId:bB,amount:75000});let delta=await pub('&revision='+revision+'&boardRevision='+boardRev);check(delta.b.light&&delta.b.state.bid===75000&&!delta.b.teams,'Bid update returns lightweight $750 / Buyer B delta');
check((await pub('&revision='+d.event.revision)).r.status===204,'Unchanged public state returns empty 204');
let sold=await send('sell',{teamId:tA,amount:75000,buyerId:bB});const saleId=d.sales[0].id;
check(d.teams.find(t=>t.id===tA).status==='SOLD','Hammer marks Team A sold');
check(d.totals.gross===75000&&d.totals.pools.find(p=>p.id===f1).gross===75000,'$750 enters correct flight pool');
check(d.totals.pools.find(p=>p.id===f1).payouts.reduce((n,r)=>n+r.amount,0)===67500,'Projected payouts exactly equal net pool');
check(d.state.teamId===tB,'Team B automatically advances onto block');
const duplicate=await send('sell',sold.body.payload,{requestId:sold.body.requestId,revision:sold.body.revision});check(duplicate.b.duplicate&&d.sales.length===1,'Duplicate SOLD request is idempotent');
await send('buyback',{saleId,percent:5000,status:'Completed'});
check(d.totals.gross===75000,'50% buyback leaves pool at $750');
check(d.ownership.filter(o=>o.saleId===saleId&&o.status==='Completed').map(o=>o.percent).sort().join(',')==='5000,5000','Buyer B and Team A own 50% each');
check(d.ownership.find(o=>o.saleId===saleId&&o.kind==='team').consideration===37500,'Buyback consideration is $375');
await send('sale_edit',{id:saleId,amount:90000,buyerId:bB,notes:'Wrong price rehearsal'});check(d.totals.gross===90000,'Sale price correction updates total');
await send('undo');check(d.totals.gross===75000,'Undo restores $750 sale and totals');check(d.ownership.find(o=>o.kind==='team').consideration===37500,'Undo restores buyback consideration');
await read();publicData=(await pub()).b;check(publicData.totals.gross===75000&&d.totals.gross===75000,'Independent admin/public refreshes persist state');
const publicText=JSON.stringify(publicData);check(!/PRIVATE_CONTACT|SECRET_TEAM|SECRET_BUYER|privateNotes|contact/.test(publicText),'Public data excludes contacts and private notes');
await send('status',{status:'PAUSED'});await send('bid',{teamId:tB,buyerId:bA,amount:50000},{expected:400});check(d.event.status==='PAUSED','Paused auction rejects bids');await send('status',{status:'LIVE'});
const currentRevision=d.event.revision;
const race=await Promise.all([50000,55000].map(amount=>fetch(base+'/api/admin',{method:'POST',headers:{cookie,origin:base,'content-type':'application/json'},body:JSON.stringify({action:'bid',payload:{teamId:tB,buyerId:bA,amount},eventId,revision:currentRevision,requestId:crypto.randomUUID()})})));check(race.map(r=>r.status).sort().join(',')==='200,409','Concurrent operators: one wins, one safely conflicts');await read();
await send('payout_save',{poolId:f1,percent:[7000,2000]},{expected:400});check(d.payoutRules.filter(r=>r.poolId===f1).reduce((n,r)=>n+r.percent,0)===10000,'Invalid payout total rejected atomically');
await send('team_flight',{ids:[tA],flightId:f2});check(d.totals.pools.find(p=>p.id===f1).gross===0&&d.totals.pools.find(p=>p.id===f2).gross===75000,'Moving sold team recalculates both flight pools');
await send('team_status',{id:tA,status:'WITHDRAWN'},{expected:400});check(d.totals.gross===75000,'Sold team cannot silently withdraw and corrupt pool');
const eventPayload=()=>{const {name,calcuttaName,course,dates,auctionAt,description,rules,currency,settings}=d.event;return {name,calcuttaName,course,dates,auctionAt,description,rules,currency,settings};};
await send('event_update',{...eventPayload(),settings:{...d.event.settings,showBid:false,showBidder:false,showBuyer:false,showSalePrice:false,showUpcoming:false,showHandicap:false,showBuyback:false,showTotalPool:false,showFlightPools:false,showPayouts:false}});
const hidden=(await pub()).b;check(hidden.state.bid===undefined&&hidden.state.buyer===undefined,'Hidden live bid and bidder excluded server-side');check(hidden.sales.every(x=>x.buyer===undefined&&x.amount===undefined)&&hidden.teams.every(t=>t.order===undefined&&t.handicap===undefined),'Hidden sales, order and handicaps excluded server-side');check(hidden.totals.gross===undefined&&hidden.totals.pools.length===0,'Hidden pools excluded server-side');
await send('event_update',{...eventPayload(),settings:{...defaultSettings,deductionType:'fixed',deduction:1}});check(d.totals.deduction===1&&d.totals.net===74999&&d.totals.pools.reduce((n,p)=>n+p.deduction,0)===1,'Fixed deduction allocated cent-exactly');
await send('team_status',{id:tB,status:'UNSOLD'});await send('status',{status:'COMPLETED'});
await send('results',{rows:d.teams.map(t=>({teamId:t.id,finish:t.id===tA?1:null}))});check(d.totals.entitlements.length===2,'Finishing position produces owner entitlements');check(d.totals.entitlements.reduce((n,r)=>n+r.amount,0)===d.totals.pools.find(p=>p.id===f2).payouts[0].amount,'Entitlements conserve the finishing purse');
await send('sale_void',{id:saleId,notes:'Rehearsal void'});check(d.totals.gross===0&&d.totals.entitlements.length===0,'Void removes pool contribution and entitlements');
await send('undo');check(d.totals.gross===75000,'Undo void restores sale');
await send('sale_reopen',{id:saleId,notes:'Rehearsal reopen'});check(d.teams.find(t=>t.id===tA).status==='UPCOMING'&&d.totals.gross===0,'Reopen returns team to auction without old pool contribution');
await send('undo');
await send('operator_add',{email:'rehearsal-operator@example.test'});let adminRead=await read();check(adminRead.operators.some(o=>o.email==='rehearsal-operator@example.test'),'Owner grants additional operator access');await send('operator_remove',{email:'rehearsal-operator@example.test'});adminRead=await read();check(!adminRead.operators.some(o=>o.email==='rehearsal-operator@example.test'),'Owner revokes additional operator access');
for(let i=0;i<500;i++){const total=1+Math.floor(Math.random()*10000000),a=Math.floor(Math.random()*10001),b=Math.floor(Math.random()*(10001-a)),split=splitCents(total,[a,b,10000-a-b]);assert.equal(split.reduce((x,y)=>x+y,0),total);assert.ok(split.every(Number.isSafeInteger));}check(true,'500 randomized cent-exact payout splits');
check(parsePaste('"Smith, Jones",John,Mike,Championship Flight,8.4')[0][0]==='Smith, Jones','Quoted CSV round trip');
await send('results',{rows:d.teams.map(t=>({teamId:t.id,finish:null}))});
await send('event_update',{...eventPayload(),settings:{...defaultSettings,poolMode:'combined'}});check(d.totals.pools.length===1&&d.totals.pools[0].gross===75000,'Combined pool retains active sales');
await send('event_update',{...eventPayload(),settings:{...defaultSettings,poolMode:'custom'}});await send('flight_save',{id:f2,name:'First Flight',color:'#879771',ownPool:false});check(d.totals.pools.some(p=>p.id==='combined'&&p.gross===75000),'Custom flight membership uses shared pool');
await send('buyback',{saleId,percent:2500,status:'Completed'});check(d.ownership.find(o=>o.kind==='team').percent===2500&&d.totals.gross===75000,'Partial buyback changes ownership only');
await send('buyback',{saleId,percent:2500,status:'Declined'});check(d.ownership.find(o=>o.kind==='buyer').percent===10000,'Declined buyback restores full purchaser ownership');
await send('event_update',{...eventPayload(),settings:{...d.event.settings,buybackDeadline:'2000-01-01T00:00:00Z'}});await send('buyback',{saleId,percent:5000,status:'Completed'},{expected:400});check(true,'Past buyback deadline rejects completion');
await send('event_update',{...eventPayload(),settings:{...d.event.settings,buybackDeadline:''}});
await send('team_import',{teams:Array.from({length:96},(_,i)=>({name:'Scale team '+String(i+1).padStart(3,'0'),players:['Fictional '+i+' A','Fictional '+i+' B'],flightId:i%2?f1:f2}))});check(d.teams.length===100,'100-team event imports and persists');
const scale=await pub();check(scale.b.teams.length===100&&JSON.stringify(scale.b).length<100000,'100-team public board remains under 100 KB');
const mainEventId=eventId;await send('load_demo');const demoTestId=eventId;await send('reset_demo',{confirmation:'WRONG'},{expected:400});check(d.teams.length===12,'Demo reset requires exact confirmation');await send('reset_demo',{confirmation:'RESET DEMO DATA'});check(d.teams.length===0&&d.sales.length===0&&d.totals.gross===0,'Demo reset clears auction records');await send('undo');check(d.teams.length===12&&d.sales.length===5,'Undo demo reset restores records');
const report={checks,eventIds:[mainEventId,demoTestId],at:new Date().toISOString(),status:'passed'};writeFileSync('.sites-runtime/acceptance-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
