import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
const directory = mkdtempSync(join(tmpdir(), 'calcutta-auth-'));
process.env.DATABASE_PATH = join(directory, 'auth.sqlite');
process.env.ADMIN_EMAILS = 'owner@example.com';
process.env.PUBLIC_ORIGIN = 'http://localhost:5181';
const migrate = () => spawnSync(process.execPath, ['portable/migrate.mjs'], { encoding: 'utf8' });
assert.equal(migrate().status, 0); assert.equal(migrate().status, 0);
const otherPlatform = join(directory, 'other-platform');
mkdirSync(join(otherPlatform, 'drizzle'), { recursive: true });
for (const name of readdirSync('drizzle').filter(n => n.endsWith('.sql')))
  writeFileSync(join(otherPlatform, 'drizzle', name), readFileSync(join('drizzle', name), 'utf8').replace(/\r?\n/g, '\r\n'));
const moved = spawnSync(process.execPath, [resolve('portable/migrate.mjs')], { cwd: otherPlatform, encoding: 'utf8' });
assert.equal(moved.status, 0, moved.stderr);
const { getDatabase } = await import('../portable/runtime.mjs');
const { passwordHash, verifyPassword, safeReturn, createSession, readSession, checkLocal, cookie } = await import('../portable/sessions.mjs');
const { GET, POST } = await import('../portable/auth-handler.mjs');
try {
  const password = 'synthetic fixture password only', encoded = passwordHash(password);
  assert(verifyPassword(password, encoded)); assert(!verifyPassword('wrong', encoded));
  assert(!verifyPassword(password, 'invalid'));
  for (const path of ['//evil.test', '/\\evil.test', 'https://evil.test', '/api/auth/google']) assert.equal(safeReturn(path), '/');
  assert.equal(safeReturn('/admin?event=test'), '/admin?event=test');
  assert(cookie('test', 'value', 1).includes('HttpOnly'));
  const token = createSession({ kind: 'test' });
  assert.equal(readSession(token)?.kind, 'test'); assert.equal(readSession(token, true)?.kind, 'test'); assert.equal(readSession(token), null);
  assert.equal(readSession(createSession({ kind: 'expired' }, -1)), null);
  const db = getDatabase().connection;
  db.prepare('INSERT INTO portable_credentials VALUES (?,?)').run('owner@example.com', encoded);
  assert(checkLocal('owner@example.com', password));
  for (let i=0; i<5; i++) assert(!checkLocal('owner@example.com', 'wrong'));
  assert(!checkLocal('owner@example.com', password));
  db.prepare('DELETE FROM portable_login_attempts').run();
  const req = (path, options = {}) => new Request(process.env.PUBLIC_ORIGIN + path, options);
  assert.equal((await GET(req('/api/auth/google'))).status, 503);
  assert.equal((await GET(req('/api/auth/callback?code=forged&state=forged'))).status, 400);
  const page = await GET(req('/signin-with-chatgpt?return_to=/admin?event=test'));
  const loginCookie = page.headers.get('set-cookie').split(';')[0];
  const csrf = loginCookie.split('=')[1];
  const body = new URLSearchParams({ csrf, email: 'owner@example.com', password });
  assert.equal((await POST(req('/api/auth/local', { method: 'POST', headers: { origin: 'https://evil.test', cookie: loginCookie }, body }))).status, 403);
  const signedIn = await POST(req('/api/auth/local', { method: 'POST', headers: { origin: process.env.PUBLIC_ORIGIN, cookie: loginCookie }, body }));
  assert.equal(signedIn.status, 303); assert.equal(signedIn.headers.get('location'), '/admin?event=test');
  const sessionCookie = signedIn.headers.get('set-cookie').split(';')[0];
  const session = sessionCookie.split('=')[1];
  assert.equal(readSession(session).user.email, 'owner@example.com');
  assert.equal((await POST(req('/api/auth/local', { method: 'POST', headers: { origin: process.env.PUBLIC_ORIGIN, cookie: loginCookie }, body }))).status, 403);
  const logout = await GET(req('/signout-with-chatgpt'));
  const logoutCookie = logout.headers.get('set-cookie').split(';')[0];
  const result = await POST(req('/api/auth/logout', { method: 'POST', headers: { origin: process.env.PUBLIC_ORIGIN, cookie: logoutCookie + '; ' + sessionCookie }, body: new URLSearchParams({ csrf: logoutCookie.split('=')[1] }) }));
  assert.equal(result.status, 303); assert.equal(readSession(session), null);
  console.log('Portable auth passed: password hashing, throttle, CSRF, replay, session expiry/revocation, safe redirects, missing Google config and forged callback denial.');
} finally { getDatabase().close(); rmSync(directory, { recursive: true, force: true }); }
