import assert from 'node:assert/strict';
import fs from 'node:fs';
import QRCode from 'qrcode';
import jsQR from 'jsqr';
import {PNG} from 'pngjs';
import {shareLinks} from '../lib/sharing.ts';
import {exportRows} from '../lib/exports.ts';
import {defaultSettings,normalizeSettings} from '../lib/model.ts';
const base=process.env.CALCUTTA_TEST_URL||'http://localhost:5173';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw Error('Test writes require localhost.');
let checks=0;function check(ok,label){assert.ok(ok,label);checks++;console.log('PASS '+label);}
const {testSession}=await import('./test-session.mjs'),cookie=await testSession(base);
let eventId,d;
async function read(){const r=await fetch(base+'/api/admin?event='+eventId,{headers:{cookie}});assert.equal(r.status,200);const body=await r.json();d=body.data;return body;}
async function send(action,payload={},opts={}){const body={action,payload,eventId,revision:d?.event.revision,requestId:crypto.randomUUID(),...opts};const r=await fetch(base+'/api/admin',{method:'POST',headers:{cookie,origin:base,'content-type':'application/json'},body:JSON.stringify(body)});const result=await r.json();assert.equal(r.status,opts.expected||200,action+': '+JSON.stringify(result));if(result.eventId){eventId=result.eventId;fs.writeFileSync('.sites-runtime/refinement-event.json',JSON.stringify({eventId}));}await read();return {result,body};}
async function settings(p){await send('event_update',{...d.event,settings:{...d.event.settings,...p}});}
async function pub(q=''){return await (await fetch(base+'/api/public?event='+eventId+q)).json();}
await send('create_event',{name:'Refinement rehearsal '+new Date().toISOString(),course:'Fictional QA course'});
check(!d.event.settings.trackBidder && d.event.settings.buybackMode==='off','New event defaults to amount-only bidding and buybacks Off');
check(normalizeSettings({minBid:100}).trackBidder&&normalizeSettings({minBid:100}).buybackMode==='track','Legacy settings retain existing bidder/ownership behavior');
await send('flight_save',{name:'Championship',color:'#b79a59',ownPool:true});const fid=d.flights[0].id;
await send('team_import',{teams:['North / West','Lake / Field','Pine / Oak','Green / Gold'].map(name=>({name,players:name.split(' / '),flightId:fid}))});const [a,b,c,four]=d.teams.map(t=>t.id);
await send('buyer_save',{name:'QA Johnson Group',contact:'PRIVATE_CONTACT_X',privateNotes:'PRIVATE_BUYER_NOTES_X'});const buyer=d.buyers[0].id;
await send('buyer_save',{name:'QA Second Buyer'});const second=d.buyers.find(b=>b.id!==buyer).id;
await send('status',{status:'LIVE'});
check(d.state.bid===0&&d.state.teamId===a,'First team starts with zero bid');
await send('bid',{teamId:a,amount:d.event.settings.quickStarts[0]});
check(d.state.bid===10000&&d.state.buyerId===null,'Quick Start records opening amount without a buyer');
let publicData=await pub();check(publicData.state.bid===10000&&publicData.state.buyer===undefined&&!publicData.event.settings.trackBidder,'Public opening bid is unattributed');
await send('bid',{teamId:a,amount:d.state.bid+d.event.settings.quickIncrements[0],buyerId:buyer});
check(d.state.bid===12500&&d.state.buyerId===null,'Increment adds correctly; disabled bidder tracking ignores supplied buyer');
await send('sell',{teamId:a,amount:12500},{expected:400});check(d.sales.length===0,'Sold requires a final purchaser');
await send('sell',{teamId:a,amount:12501,buyerId:buyer},{expected:409});check(d.sales.length===0,'Sold rejects a different final price');
const sold=await send('sell',{teamId:a,amount:12500,buyerId:buyer}),saleA=d.sales[0].id;
check(d.sales[0].buyerId===buyer&&d.state.teamId===b,'Sold records final purchaser and advances');
check(d.ownership.filter(o=>o.saleId===saleA).length===1&&d.ownership[0].percent===10000,'Buyback Off creates only full purchaser ownership');
check((await pub()).sales[0].buyer==='QA Johnson Group','Confirmed buyer appears publicly after sale');
await send('sell',sold.body.payload,{revision:sold.body.revision,requestId:sold.body.requestId});check(d.sales.length===1,'Repeated exact sale request remains idempotent');
await send('buyback',{saleId:saleA,percent:5000,status:'Completed'},{expected:400});check(d.totals.gross===12500,'Off rejects ownership mutations');
await settings({buybackMode:'calculate',buybackSuggested:3333,buybackDeadline:'2000-01-01T00:00:00Z'});
check(Math.round(d.sales[0].amount*d.event.settings.buybackSuggested/10000)===4166,'Calculation-only custom suggestion rounds to cents');
await send('buyback',{saleId:saleA,percent:2500,status:'Completed'},{expected:400});check(d.ownership.length===1&&d.totals.gross===12500,'Calculation only does not alter ownership or pools');
await send('bid',{teamId:b,amount:20000});await send('sell',{teamId:b,amount:20000,buyerId:buyer});
check(d.settlement.receipts[0].purchases.length===2&&d.settlement.purchases===32500,'One buyer account aggregates multiple purchases');
check(d.settlement.receivable===32500&&d.settlement.received===0,'Suggested private buyback is excluded from club receivables');
await settings({trackBidder:true,buybackMode:'track',buybackDeadline:''});
await send('bid',{teamId:c,amount:30000,buyerId:second});check(d.state.buyerId===second&&(await pub()).state.buyer==='QA Second Buyer','Enabled bidder tracking is preserved publicly');
const liveRevision=d.event.revision,boardRevision=d.event.boardRevision;
await send('bid',{teamId:c,amount:32500});publicData=await pub('&revision='+liveRevision+'&boardRevision='+boardRevision);check(publicData.light&&publicData.state.buyer===undefined&&d.state.buyerId===null,'Optional tracking accepts unattributed bids and clears misleading identity');
await send('sell',{teamId:c,amount:32500,buyerId:second},{revision:liveRevision,expected:409});check(d.sales.length===2,'Stale sale dialog cannot sell after another bid');
await send('sell',{teamId:c,amount:32500,buyerId:second});const saleC=d.sales.find(s=>s.teamId===c).id;
await send('buyback',{saleId:saleA,percent:5000,status:'Completed'});
check(d.totals.gross===65000&&d.settlement.purchases===65000,'Tracked buyback changes neither gross pool nor club receivables');
check(d.ownership.filter(o=>o.saleId===saleA&&o.status==='Completed').reduce((n,o)=>n+o.percent,0)===10000,'Tracked ownership reconciles to 100%');
const receipt={kind:'receipt',partyKind:'buyer',partyId:buyer,amount:10000,occurredAt:new Date().toISOString(),method:'Check',note:'QA_PRIVATE_REF_100'};
const payment=await send('settlement_record',receipt),paymentId=payment.result.recordId;
check(d.settlement.receipts.find(r=>r.id===buyer).balance===22500&&d.settlement.receipts.find(r=>r.id===buyer).status==='Partial','Partial receipt updates outstanding balance');
await send('settlement_record',receipt,{requestId:payment.body.requestId,revision:payment.body.revision});check(d.payments.length===1,'Payment recording is idempotent');
await send('settlement_record',{...receipt,amount:22500,method:'Cash'});check(d.settlement.receipts.find(r=>r.id===buyer).status==='Paid','Final receipt produces Paid status');
await read();check(d.payments.length===2&&d.settlement.received===32500,'Transaction records survive independent refresh');
await send('settlement_record',{...receipt,amount:1},{expected:400});check(d.payments.length===2,'Overpayment entry is rejected');
await send('settlement_reverse',{kind:'receipt',id:paymentId,note:'Wrong check amount'});check(d.payments.length===3&&d.payments.find(p=>p.id===paymentId).amount===10000&&d.settlement.received===22500,'Correction retains original and appends signed reversal');
await send('settlement_reverse',{kind:'receipt',id:paymentId,note:'Duplicate correction'},{expected:400});check(d.payments.length===3,'Duplicate reversal rejected');
let audit=(await read()).audit;check(audit.some(a=>a.action==='settlement_reverse'&&a.recordId),'Payment correction is audited');
await send('undo');check(d.payments.length===4&&d.settlement.received===32500,'Undo reversal adds compensation and retains transaction trail');
await send('settlement_record',{...receipt,partyId:second,amount:5000});const added=d.payments.length;await send('undo');check(d.payments.length===added+1&&d.settlement.receipts.find(r=>r.id===second).paid===0,'Undo payment adds a reversal without deleting the payment');
await send('sale_edit',{id:saleA,amount:10000,buyerId:buyer,notes:'QA overpayment scenario'});check(d.settlement.receipts.find(r=>r.id===buyer).status==='Overpaid','Sale correction reveals overpayment without moving receipts');
await send('undo');check(d.settlement.receipts.find(r=>r.id===buyer).status==='Paid'&&d.payments.length===added+1,'Auction undo retains settlement history');
publicData=await pub();check(!/payments|disbursements|settlement|QA_PRIVATE_REF|PRIVATE_CONTACT_X|PRIVATE_BUYER_NOTES/.test(JSON.stringify(publicData)),'Public API excludes settlement details and private data');
await send('team_save',{name:'Extra queue team',players:['Extra','Queue'],flightId:fid});const extra=d.teams.at(-1).id;
const order=d.teams.map(t=>t.id);await send('team_skip',{id:four});check(d.teams.at(-1).id===four&&d.teams.find(t=>t.id===four).status==='UPCOMING'&&d.state.teamId===extra&&d.totals.gross===65000,'Skip current team moves it to queue end, clears bid and preserves finances');
await send('undo');check(JSON.stringify(d.teams.map(t=>t.id))===JSON.stringify(order)&&d.state.teamId===four,'Undo skip restores queue position and block');
await send('team_skip',{id:extra});check(d.teams.at(-1).id===extra&&d.state.teamId===four&&d.teams.find(t=>t.id===extra).status==='UPCOMING','Skip queued team leaves current block untouched');
await send('team_status',{id:four,status:'UNSOLD'});check(d.teams.find(t=>t.id===four).status==='UNSOLD'&&d.state.teamId===null,'Mark Unsold is distinct and removes team from queue');
await send('payout_save',{poolId:fid,percent:[6000,3000]},{expected:400});check(d.payoutRules.reduce((n,r)=>n+r.percent,0)===10000,'Incomplete payout ladder rejected');
await send('payout_save',{poolId:fid,percent:[6000,3000,999,1]});check(d.totals.pools[0].payouts.reduce((n,r)=>n+r.amount,0)===d.totals.net,'Custom four-place ladder reconciles to the cent');
await send('payout_save',{poolId:fid,percent:[7000,3000]});check(d.totals.pools[0].payouts.length===2,'Payout ladder supports removal and replacement');
await send('status',{status:'COMPLETED'});await send('results',{rows:d.teams.map(t=>({teamId:t.id,finish:t.id===a?1:t.id===b?2:null}))});
check(d.settlement.entitled===d.totals.net&&d.settlement.payables.some(r=>r.kind==='team'),'Payout payables respect completed team buyback ownership');
check(d.settlement.receipts.find(r=>r.id===buyer).balance===0&&d.settlement.payable===d.totals.net,'Receivables and payout payables are never automatically netted');
const payee=d.settlement.payables.find(p=>p.kind==='team');
const disbursement=await send('settlement_record',{kind:'payout',partyKind:'team',partyId:payee.id,amount:payee.balance,occurredAt:new Date().toISOString(),method:'Other',note:'QA payout completed'});
check(d.settlement.payables.find(p=>p.kind==='team').status==='Paid'&&d.disbursements.length===1,'Manual payout completion records a separate disbursement');
await send('settlement_reverse',{kind:'payout',id:disbursement.result.recordId,note:'Payout correction'});check(d.settlement.disbursed===0&&d.disbursements.length===2,'Payout reversal retains original disbursement');
await send('undo');check(d.settlement.disbursed===payee.balance&&d.disbursements.length===3,'Payout reversal undo retains compensation history');
const settlementRows=exportRows(d,'settlement').slice(1);check(settlementRows.reduce((n,r)=>n+Math.round(Number(r[4])*100),0)===d.totals.gross&&settlementRows.reduce((n,r)=>n+Math.round(Number(r[5])*100),0)===d.settlement.received,'Settlement export reconciles purchases and receipts');
const auctionRows=exportRows(d,'auction').slice(1);check(auctionRows.filter(r=>r[9]==='ACTIVE').reduce((n,r)=>n+Math.round(Number(r[8])*100),0)===d.totals.gross,'Auction export reconciles active sales');
check(exportRows(d,'payouts').slice(1).reduce((n,r)=>n+Math.round(Number(r[11])*100),0)===d.settlement.entitled,'Payout export reconciles entitlement rows');
for(const kind of ['auction','settlement','teams','payouts','ownership','payments','backup']) {const r=await fetch(base+'/api/export?event='+eventId+'&kind='+kind,{headers:{cookie}});check(r.status===200&&r.headers.get('content-disposition').includes('attachment'),'Authenticated '+kind+' export downloads');const text=await r.text();if(kind==='backup'){const backup=JSON.parse(text);check(backup.data.payments.length===d.payments.length&&backup.audit.some(r=>r.action==='settlement_record')&&backup.privateFieldsIncluded,'Full backup contains relational payments and complete audit');}else if(kind!=='payments')check(!text.includes('PRIVATE_CONTACT_X')&&!text.includes('PRIVATE_BUYER_NOTES'),'Standard '+kind+' CSV omits private contact fields');}
check((await fetch(base+'/api/export?event='+eventId+'&kind=backup')).status===403,'Anonymous event backup export denied');
check((await fetch(base+'/api/export?event='+eventId+'&kind=payments',{headers:{'oai-authenticated-user-id':'forged','oai-authenticated-user-email':'seedy@sites.test'}})).status===403,'Forged headers cannot access settlement exports');
for(const origin of [base,'https://calcutta.example']){const links=shareLinks(origin,eventId);check(new URL(links.board).pathname==='/'&&new URL(links.tv).pathname==='/tv'&&[...new URL(links.board).searchParams.keys()].join(',')==='event','Share links contain only view route and event ID at '+origin);const png=PNG.sync.read(await QRCode.toBuffer(links.board,{width:480,margin:4}));const decoded=jsQR(new Uint8ClampedArray(png.data),png.width,png.height);check(decoded?.data===links.board,'Decoded QR contains exactly the public URL at '+origin);}
check(shareLinks(base,eventId).local&&!shareLinks('https://calcutta.example',eventId).local,'Local sharing flag distinguishes development links');
await settings({buybackMode:'off',trackBidder:false});check(d.ownership.some(o=>o.kind==='team'&&o.percent===5000)&&d.settlement.entitled===d.totals.net,'Disabling buyback tools preserves completed ownership and entitlements');
check((await pub()).sales.every(s=>s.ownership===undefined),'Buyback Off hides ownership in public payload');
const report={checks,eventId,at:new Date().toISOString(),status:'passed',payments:d.payments.length,disbursements:d.disbursements.length};fs.writeFileSync('.sites-runtime/refinement-report.json',JSON.stringify(report,null,2));fs.writeFileSync('.sites-runtime/refinement-persistence.json',JSON.stringify({eventId,payments:d.payments,disbursements:d.disbursements,settlement:d.settlement}));console.log(JSON.stringify(report));
