"use client";
import { useState, useEffect } from 'react';
import { Plus, ArrowUp, ArrowDown, X, Gavel } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Combobox, ComboboxInput, ComboboxContent, ComboboxList, ComboboxItem, ComboboxEmpty } from '@/components/ui/combobox';
import { Choice } from './auction';
import { Field } from './operator';
import { money, splitCents, type Row } from '@/lib/model';

export function BuyerPicker({ buyers, value, onChange, label = 'Final purchaser' }: any) {
    return <Combobox items={buyers} value={buyers.find((b: Row) => b.id === value) || null} onValueChange={(v: Row | null) => onChange(v?.id || '')} itemToStringLabel={(b: Row) => b.name}><ComboboxInput aria-label={label} placeholder="Search buyers or syndicates…"/><ComboboxContent><ComboboxEmpty>No matching buyer. Use Add buyer below.</ComboboxEmpty><ComboboxList>{(b: Row) => <ComboboxItem key={b.id} value={b}>{b.name}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox>;
}
export function SoldDialog({ sale, setSale, data, act, busy }: any) {
    const [adding, setAdding] = useState(false), [name, setName] = useState('');
    const recent = [...new Set(data.sales.filter((s: Row) => s.status === 'ACTIVE').map((s: Row) => s.buyerId))].slice(0, 5).map(id => data.buyers.find((b: Row) => b.id === id)).filter(Boolean);
    const stale = sale.revision !== data.event.revision;
    // Escape while the buyer suggestion list is open closes only the list (the combobox handles it); the next Escape closes the dialog.
    const escapeClosesListFirst = (ev: KeyboardEvent) => { const target = ev.target as HTMLElement | null; if (target?.getAttribute('role') === 'combobox' && target.getAttribute('aria-expanded') === 'true') ev.preventDefault(); };
    return <Dialog open onOpenChange={open => { if (!open && !busy) setSale(null); }}><DialogContent className="sale-dialog" onEscapeKeyDown={escapeClosesListFirst}><DialogHeader><DialogTitle>Bring down the hammer</DialogTitle><DialogDescription>Select the final purchaser and confirm this exact team and price.</DialogDescription></DialogHeader><div className="sale-summary"><div><span className="eyebrow">TEAM</span><h2>{sale.teamName}</h2></div><div><span className="eyebrow">FINAL PRICE</span><strong>{money(sale.amount, data.event.currency)}</strong></div></div><Field label="Buyer / syndicate"><BuyerPicker buyers={data.buyers} value={sale.buyerId} onChange={(buyerId: string) => setSale({ ...sale, buyerId })}/></Field>{recent.length > 0 && <div><p className="eyebrow">RECENT BUYERS</p><div className="buyer-chips">{recent.map(b => <Button key={b.id} variant={sale.buyerId === b.id ? 'default' : 'outline'} size="sm" onClick={() => setSale({ ...sale, buyerId: b.id })}>{b.name}</Button>)}</div></div>}{adding ? <form className="inline-buyer" onSubmit={async ev => { ev.preventDefault(); const result = await act('buyer_save', { name }, { revision: sale.revision }); if (result) { setSale({ ...sale, buyerId: result.recordId, revision: result.revision }); setAdding(false); setName(''); } }}><Field label="New buyer name"><Input autoFocus required maxLength={150} value={name} onChange={ev => setName(ev.target.value)}/></Field><Button disabled={busy || stale}>Add & select</Button><Button type="button" variant="ghost" onClick={() => setAdding(false)}>Cancel</Button></form> : <Button variant="ghost" className="add-buyer" onClick={() => setAdding(true)}><Plus/> Add buyer here</Button>}{stale && <p className="notice" role="alert">The auction changed while this dialog was open. Close it and press Hammer / sold again to review the latest bid.</p>}<div className="dialog-actions"><Button variant="outline" disabled={busy} onClick={() => setSale(null)}>Cancel</Button><Button className="hammer" disabled={busy || stale || !sale.buyerId || adding} onClick={async () => { if (await act('sell', { teamId: sale.teamId, amount: sale.amount, buyerId: sale.buyerId }, { revision: sale.revision, message: 'Sold — purchaser recorded' })) setSale(null); }}><Gavel/> Confirm sale</Button></div></DialogContent></Dialog>;
}
function moved<T>(rows: T[], i: number, delta: number) { const next = [...rows]; [next[i], next[i + delta]] = [next[i + delta], next[i]]; return next; }
export function AmountEditor({ label, values, onChange, currency }: any) {
    return <fieldset className="structured-editor"><legend>{label}</legend><div className="amount-rows">{values.map((amount: number, i: number) => <div className="amount-editor-row" key={i}><span>{currency}</span><Input aria-label={label + ' amount ' + (i + 1)} type="number" min=".01" max="1000000" step=".01" required value={amount ? amount / 100 : ''} onChange={ev => onChange(values.map((v: number, j: number) => i === j ? Math.round(Number(ev.target.value) * 100) : v))}/><Button type="button" variant="ghost" size="icon" aria-label={label + ' move ' + (i + 1) + ' up'} disabled={!i} onClick={() => onChange(moved(values, i, -1))}><ArrowUp/></Button><Button type="button" variant="ghost" size="icon" aria-label={label + ' move ' + (i + 1) + ' down'} disabled={i === values.length - 1} onClick={() => onChange(moved(values, i, 1))}><ArrowDown/></Button><Button type="button" variant="ghost" size="icon" aria-label={label + ' remove ' + (i + 1)} disabled={values.length === 1} onClick={() => onChange(values.filter((_: number, j: number) => j !== i))}><X/></Button></div>)}</div><Button type="button" variant="outline" size="sm" disabled={values.length >= 8} onClick={() => onChange([...values, 0])}><Plus/> Add amount</Button></fieldset>;
}
const presets: Record<string, number[]> = { '70 / 30': [7000,3000], '70 / 20 / 10': [7000,2000,1000], '60 / 30 / 10': [6000,3000,1000], '50 / 30 / 20': [5000,3000,2000], '40 / 30 / 20 / 10': [4000,3000,2000,1000] };
export function PayoutLadder({ pool, data, busy, act, ask }: any) {
    const initial = data.payoutRules.filter((r: Row) => r.poolId === pool.id).map((r: Row) => r.percent);
    const [rows, setRows] = useState<number[]>(initial.length ? initial : [5000,3000,2000]), [preset, setPreset] = useState('custom'), [revision, setRevision] = useState(data.event.revision), [dirty, setDirty] = useState(false);
    const saved = JSON.stringify(initial.length ? initial : [5000,3000,2000]);
    useEffect(() => { if (!dirty || saved === JSON.stringify(rows)) { setRows(JSON.parse(saved)); setRevision(data.event.revision); setDirty(false); } }, [saved, data.event.revision, dirty]);
    const total = rows.reduce((n, r) => n + r, 0), valid = total === 10000 && rows.every(r => r >= 0 && r <= 10000), current = data.totals.pools.find((p: Row) => p.id === pool.id), net = current?.net || 0;
    const amounts = valid ? splitCents(net, rows) : [];
    const change = (v: number[]) => { if (!dirty) setRevision(data.event.revision); setDirty(true); setRows(v); setPreset('custom'); };
    return <section className="payout-ladder"><h3>{pool.name}</h3><Choice label={'Payout preset ' + pool.name} value={preset} onChange={(v: string) => { if(!dirty) setRevision(data.event.revision); setDirty(true); setPreset(v); if (v !== 'custom') setRows(presets[v]); }} items={[{value:'custom',label:'Custom'}, ...Object.keys(presets)]}/><div className="ladder-labels"><span>Place</span><span>Percentage</span><span>Projected payout</span></div>{rows.map((pct, i) => <div className="ladder-row" key={i}><strong>{i + 1}{i === 0 ? 'st' : i === 1 ? 'nd' : i === 2 ? 'rd' : 'th'}</strong><div className="percent-input"><Input aria-label={pool.name + ' place ' + (i + 1) + ' percent'} type="number" min="0" max="100" step=".01" value={pct / 100} onChange={ev => change(rows.map((v, j) => i === j ? Math.round(Number(ev.target.value) * 100) : v))}/><span>%</span></div><span className="projected">{valid ? money(amounts[i], data.event.currency) : '—'}</span><div className="row-tools"><Button size="icon" variant="ghost" aria-label={'Move payout place ' + (i + 1) + ' up in ' + pool.name} disabled={!i} onClick={() => change(moved(rows, i, -1))}><ArrowUp/></Button><Button size="icon" variant="ghost" aria-label={'Move payout place ' + (i + 1) + ' down in ' + pool.name} disabled={i === rows.length - 1} onClick={() => change(moved(rows, i, 1))}><ArrowDown/></Button><Button size="icon" variant="ghost" aria-label={'Remove payout place ' + (i + 1) + ' in ' + pool.name} disabled={rows.length === 1} onClick={() => change(rows.filter((_, j) => j !== i))}><X/></Button></div></div>)}<div className={'ladder-total ' + (valid ? 'valid' : 'invalid')} role="status"><span>Total</span><strong>{(total / 100).toFixed(2)}% {valid ? '✓' : '· must equal 100%'}</strong></div><div className="actions"><Button size="sm" variant="outline" disabled={rows.length >= 10} onClick={() => change([...rows, 0])}><Plus/> Add place</Button><Button size="sm" disabled={busy || !valid} onClick={async () => { if (data.totals.gross || data.teams.some((t: Row) => t.finish)) { ask('Change the payout ladder?', 'This recalculates projected purses and any existing payout entitlements. Recorded payments stay in the settlement history; review balances afterward.', 'payout_save', {poolId:pool.id,percent:rows}, {revision}); } else { const result = await act('payout_save', {poolId:pool.id,percent:rows}, {revision}); if(result) setRevision(result.revision); } }}>Save {pool.name} payouts</Button></div><p className="fine">{current ? 'Amounts use the current net pool and reconcile to the cent.' : 'This ladder is saved for when this pool is used.'}</p></section>;
}
