"use client";
import { useState } from 'react';
import { Download, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { money, type Row } from '@/lib/model';
export function Exports({data}: any) {
    const [busy,setBusy]=useState('');
    const reports=[['auction','Auction Results CSV','All sale records, purchasers, flights and prices. Use ACTIVE rows for the current auction pool.'],['settlement','Buyer Settlement CSV','Purchase totals, recorded payments and remaining balances.'],['teams','Teams & Flights CSV','The field, players, queue order and finishing positions.'],['payouts','Final Results / Payouts CSV','Each ownership entitlement and the payee’s settlement status.'],...(data.event.settings.buybackMode!=='off'||data.ownership.some((o:Row)=>o.kind==='team')?[['ownership','Ownership / Buyback CSV','Ownership agreements and private buyback consideration.']]:[]),['payments','Payment History CSV','Receipts, payouts and reversals, with notes and audit details. Administrator only.'],['backup','Full Event JSON Backup','Complete event records and audit history. Includes private contacts, private notes and operator email addresses. Store securely.']];
    async function save(kind:string) {setBusy(kind);try {const response=await fetch('/api/export?event='+encodeURIComponent(data.event.id)+'&kind='+kind);if(!response.ok)throw Error(((await response.json()) as any).error);const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download='calcutta-'+kind+(kind==='backup'?'.json':'.csv');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success('Export ready');}catch(e){toast.error(e instanceof Error?e.message:'Export unavailable');}finally{setBusy('');}}
    return <><div className="section-title"><div><p className="eyebrow">TAKE YOUR RECORDS WITH YOU</p><h2>Event exports</h2><p className="muted">Reports use the authoritative event totals. Standard CSVs omit private buyer contact details.</p></div><Button variant="outline" onClick={()=>window.print()}><Printer/> Print event summary</Button></div><div className="export-grid">{reports.map(([kind,title,description])=><section className="panel export-card" key={kind}><Download/><h3>{title}</h3><p>{description}</p><Button variant="outline" disabled={!!busy} onClick={()=>save(kind)}>{busy===kind?'Preparing…':'Download'}</Button></section>)}</div><p className="fine">Payout exports show one row per entitlement. Party totals repeat when a payee owns more than one winning team; sum Entitled Amount for total awards. A backup is a portable data archive; this pass does not add a restore/import workflow.</p><section className="print-summary"><h1>{data.event.name}</h1><p>{data.event.course} · {data.event.dates} · {data.event.status}</p><p>Gross auction pool {money(data.totals.gross,data.event.currency)} · House share {money(data.totals.deduction,data.event.currency)} · Net pool {money(data.totals.net,data.event.currency)}</p><h2>Auction receivables</h2><p>Remaining to collect {money(data.settlement.receivable,data.event.currency)} · Overpayments to review {money(data.settlement.receiptOverpayments,data.event.currency)}</p><table><thead><tr><th>Buyer</th><th>Purchases</th><th>Received</th><th>Balance</th></tr></thead><tbody>{data.settlement.receipts.map((r:Row)=><tr key={r.id}><td>{r.name}</td><td>{money(r.due,data.event.currency)}</td><td>{money(r.paid,data.event.currency)}</td><td>{money(r.balance,data.event.currency)}</td></tr>)}</tbody></table><h2>Tournament payables</h2><p>Remaining to pay {money(data.settlement.payable,data.event.currency)} · Overpayments to review {money(data.settlement.payoutOverpayments,data.event.currency)}</p><table><thead><tr><th>Party</th><th>Entitled</th><th>Recorded</th><th>Due</th></tr></thead><tbody>{data.settlement.payables.map((r:Row)=><tr key={r.kind+r.id}><td>{r.name}</td><td>{money(r.due,data.event.currency)}</td><td>{money(r.paid,data.event.currency)}</td><td>{money(r.balance,data.event.currency)}</td></tr>)}</tbody></table><h2>Sales</h2><table><thead><tr><th>Team</th><th>Buyer</th><th>Amount</th><th>Status</th></tr></thead><tbody>{data.sales.map((s:Row)=><tr key={s.id}><td>{data.teams.find((t:Row)=>t.id===s.teamId)?.name}</td><td>{data.buyers.find((b:Row)=>b.id===s.buyerId)?.name}</td><td>{money(s.amount,data.event.currency)}</td><td>{s.status}</td></tr>)}</tbody></table><p>Manual records only. Private buyback payments are excluded from club settlement.</p></section></>;
}
