import { sqliteTable, text, integer, real, uniqueIndex, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
export const events = sqliteTable("events", {
    id: text().primaryKey(), name: text().notNull(), calcuttaName: text().notNull(), course: text().notNull(), dates: text().notNull().default(""), auctionAt: text().notNull().default(""), status: text().notNull().default("SETUP"), description: text().notNull().default(""), rules: text().notNull().default(""), currency: text().notNull().default("USD"), settings: text().notNull(), demo: integer().notNull().default(0), revision: integer().notNull().default(0), boardRevision: integer().notNull().default(0), createdAt: text().notNull(), updatedAt: text().notNull()
});
export const flights = sqliteTable("flights", { id: text().primaryKey(), eventId: text().notNull().references(() => events.id, { onDelete: "cascade" }), name: text().notNull(), order: integer().notNull(), color: text().notNull().default("#b69b60"), ownPool: integer().notNull().default(1) }, t => [index("idx_flights_event").on(t.eventId)]);
export const teams = sqliteTable("teams", { id: text().primaryKey(), eventId: text().notNull().references(() => events.id, { onDelete: "cascade" }), flightId: text().notNull().references(() => flights.id), name: text().notNull(), handicap: real(), seed: integer(), notes: text().notNull().default(""), privateNotes: text().notNull().default(""), order: integer().notNull(), status: text().notNull().default("UPCOMING"), finish: integer() }, t => [index("idx_teams_event_order").on(t.eventId, t.order), check("team_status", sql `${t.status} in ('UPCOMING','ON_BLOCK','SOLD','UNSOLD','WITHDRAWN')`)]);
export const players = sqliteTable("players", { id: text().primaryKey(), teamId: text().notNull().references(() => teams.id, { onDelete: "cascade" }), name: text().notNull(), order: integer().notNull() }, t => [index("idx_players_team").on(t.teamId)]);
export const buyers = sqliteTable("buyers", { id: text().primaryKey(), eventId: text().notNull().references(() => events.id, { onDelete: "cascade" }), name: text().notNull(), group: text().notNull().default(""), contact: text().notNull().default(""), privateNotes: text().notNull().default("") }, t => [uniqueIndex("idx_buyer_event_name").on(t.eventId, t.name)]);
export const auctionState = sqliteTable("auction_state", { eventId: text().primaryKey().references(() => events.id, { onDelete: "cascade" }), teamId: text().references(() => teams.id), bid: integer().notNull().default(0), buyerId: text().references(() => buyers.id), startedAt: text(), paused: integer().notNull().default(0) }, t => [check("bid_nonnegative", sql `${t.bid} >= 0`)]);
export const sales = sqliteTable("sales", { id: text().primaryKey(), eventId: text().notNull().references(() => events.id, { onDelete: "cascade" }), teamId: text().notNull().references(() => teams.id), buyerId: text().notNull().references(() => buyers.id), amount: integer().notNull(), status: text().notNull().default("ACTIVE"), createdAt: text().notNull(), notes: text().notNull().default("") }, t => [index("idx_sales_event_status").on(t.eventId, t.status), uniqueIndex("one_active_sale_per_team").on(t.teamId).where(sql `${t.status} = 'ACTIVE'`), check("sale_amount_positive", sql `${t.amount}>0`)]);
export const ownership = sqliteTable("ownership", { id: text().primaryKey(), saleId: text().notNull().references(() => sales.id, { onDelete: "cascade" }), party: text().notNull(), percent: integer().notNull(), consideration: integer().notNull().default(0), status: text().notNull(), kind: text().notNull() }, t => [index("idx_ownership_sale").on(t.saleId), check("ownership_range", sql `${t.percent} between 0 and 10000`)]);
export const payoutRules = sqliteTable("payout_rules", { id: text().primaryKey(), eventId: text().notNull().references(() => events.id, { onDelete: "cascade" }), poolId: text().notNull(), place: integer().notNull(), percent: integer().notNull() }, t => [uniqueIndex("idx_payout_pool_place").on(t.eventId, t.poolId, t.place)]);
export const audit = sqliteTable("audit", { id: text().primaryKey(), eventId: text().notNull().references(() => events.id, { onDelete: "cascade" }), actor: text().notNull(), action: text().notNull(), recordId: text(), before: text(), after: text(), createdAt: text().notNull(), undone: integer().notNull().default(0) }, t => [index("idx_audit_event_time").on(t.eventId, t.createdAt)]);
export const operators = sqliteTable("operators", { email: text().primaryKey(), addedBy: text().notNull(), createdAt: text().notNull() });
export const mutationGuards = sqliteTable("mutation_guards", { id: text().primaryKey(), ok: integer().notNull() }, t => [check("revision_must_match", sql `${t.ok}=1`)]);
export const settlementPayments = sqliteTable("settlement_payments", {
    id: text().primaryKey(), eventId: text().notNull().references(() => events.id, { onDelete: "cascade" }), buyerId: text().notNull().references(() => buyers.id), amount: integer().notNull(), occurredAt: text().notNull(), method: text().notNull(), note: text().notNull().default(""), actor: text().notNull(), createdAt: text().notNull(), reversalOf: text()
}, t => [index("idx_payments_event_buyer").on(t.eventId, t.buyerId), uniqueIndex("one_payment_reversal").on(t.reversalOf), check("payment_amount", sql `${t.amount} != 0`)]);
export const payoutDisbursements = sqliteTable("payout_disbursements", {
    id: text().primaryKey(), eventId: text().notNull().references(() => events.id, { onDelete: "cascade" }), buyerId: text().references(() => buyers.id), teamId: text().references(() => teams.id), amount: integer().notNull(), occurredAt: text().notNull(), method: text().notNull(), note: text().notNull().default(""), actor: text().notNull(), createdAt: text().notNull(), reversalOf: text()
}, t => [index("idx_disbursements_event").on(t.eventId), uniqueIndex("one_disbursement_reversal").on(t.reversalOf), check("payout_amount", sql `${t.amount} != 0`), check("one_payee", sql `(${t.buyerId} IS NOT NULL AND ${t.teamId} IS NULL) OR (${t.buyerId} IS NULL AND ${t.teamId} IS NOT NULL)`)]);
