// Shared server-rendered account shell — the leaderboard's, with this product's name on it (WC-1).
// Keep this script-free under the auth CSP. The two products sit in one clubhouse and share
// volunteers; their sign-in screens should not look like different software.
export const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
export const accountStyle = `
:root{color-scheme:light;--brand:#173f30;--primary:#173f30;--primary-hover:#2a5a46;--surface:#f4f6f3;--border:#718276;--focus:#146c52;--live:#d5ed68;--information:#245b78;--success:#24633f;--attention:#715000;--danger:#a22927;--neutral:#53675f}
*{box-sizing:border-box}body{margin:0;font:18px/1.5 system-ui;color:#172c23;background:var(--surface);min-height:100vh;min-height:100dvh}
.account-masthead{background:var(--brand);color:#fff;padding:22px max(24px,5vw);border-bottom:4px solid var(--live)}.account-masthead a{color:inherit;text-decoration:none;font-weight:800;letter-spacing:.08em}.account-masthead span{display:block;font-size:14px;letter-spacing:.04em}
main{max-width:650px;margin:clamp(24px,6vh,64px) auto;padding:0 24px}h1{font-size:clamp(28px,5vw,36px);line-height:1.15;margin:0 0 24px}h2{font-size:22px;margin:28px 0 8px}p,h1,h2{overflow-wrap:anywhere}a{color:var(--primary);text-underline-offset:3px}a,summary{min-height:24px}footer a,.account-masthead a{display:inline-flex;align-items:center;min-height:32px}
form{margin:16px 0}label{display:block;font-weight:600;margin:16px 0}input,button,.primary-action{font:inherit;border-radius:5px}input:not([type=hidden]){display:block;background:#fff;color:#172c23;border:1px solid var(--border);padding:11px 12px;margin-top:6px;width:100%;min-width:0}button,.primary-action{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:10px 18px;border:1px solid var(--primary);background:var(--primary);color:#fff;font-weight:650;cursor:pointer;text-decoration:none}button:hover,.primary-action:hover{background:var(--primary-hover);border-color:var(--primary-hover);color:#fff}.primary-action{width:100%;margin:8px 0 16px}.secondary{background:#fff;color:var(--primary)}.secondary:hover{background:#eaf0e9;color:var(--primary)}button.danger{background:var(--danger);border-color:var(--danger);color:#fff}button.danger:hover{background:#7d1d1c;border-color:#7d1d1c}.secondary.danger{background:#fff;color:var(--danger)}.secondary.danger:hover{background:#fff0ee;color:var(--danger)}
:is(a,button,input,summary):focus-visible{outline:3px solid var(--focus);outline-offset:3px}.account-masthead a:focus-visible{outline-color:var(--live)}.skip-link{position:absolute;left:12px;top:-100px;padding:12px;background:#fff;z-index:10}.skip-link:focus{top:12px}
details{border-top:1px solid var(--border);margin-top:16px;padding-top:16px}summary{cursor:pointer;padding:8px 0;font-weight:600}.help{color:var(--information)}.notice,.error,.confirm{padding:12px 16px;border-radius:5px;margin:16px 0;border:1px solid currentColor}.notice{color:var(--success);background:#edf6ed}.error{color:var(--danger);background:#fff0ee}.confirm{color:var(--attention);background:#fff4d6}.confirm h2{margin-top:0}.operator{display:flex;flex-wrap:wrap;align-items:center;gap:12px;padding:12px 0;border-top:1px solid var(--border)}.operator span{flex:1 1 240px;overflow-wrap:anywhere}small,footer{color:var(--neutral)}footer{max-width:650px;margin:32px auto;padding:0 24px 24px;font-size:16px}main:focus{outline:none}
`;
export function accountDocument(title, body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="theme-color" content="#173f30"><title>${escapeHtml(title)} · The Calcutta</title><style>${accountStyle}</style></head><body><a class="skip-link" href="#main-content">Skip to main content</a><header class="account-masthead"><a href="/">The Calcutta</a><span>Edwards County Golf Course · Auction</span></header><main id="main-content" tabindex="-1">${body}</main><footer><a href="/">Public board</a></footer></body></html>`;
}
